### ISSUE TITLE
Bug - Filtering by evidence type no longer working

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#238]
The dropdown menu, that enables users to filter by evidence type is not working on the app. I tested it when it was first developed and it worked but that functionality appears to have dropped off in the production version. This needs to be fixed urgently as it is pretty basic to the use of the app.

**Comment by markwilliamfirth** [comment]
I can confirm testing on desktop, macbook pro, chrome on my account that this doesn't work for me either

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/bestevidence/issues/25

**Comment by iteles** [comment]
A little refactoring at the end of the last sprint threw this off kilter. The fix has been written and is under QA review before we can pass this back for testing.

**Comment by SimonLab** [comment]
@ajburls this is now ready to be tested on staging, thanks

**Comment by ajburls** [comment]
@SimonLab working well. So useful!!!! Thanks

**Comment by iteles** [comment]
From @ajburls in https://github.com/dwyl/bestevidence/issues/134#issuecomment-347547930:
> This issue that stopped working and was fixed as part of Sprint 4 is not working after this was put on the bestevidence.info site today. I just tried to show Yinka that it was working and it froze when I went to select and evidence type. When I went back to the search to try again, the search ("diabetes" returned and internal server error.

**Comment by iteles** [comment]
@ajburls We took a look into this today:
+ We couldn't replicate your freezing error (three of us tried this across multiple difference devices and internet connections - data and broadband) so this may well have been an isolated incident due to your device or connection at the time, but please do keep an eye out for if it happens again
+ For the internal server error: we found that the cause of this was that with a very specific edge case around capitalisation, duplicate searches were being saved to the database and causing the server error -> we have created the fix for this and deployed it, so please go ahead and test this. 

You should be able to search for the same thing twice, once with uppercase and once with lowercase and no issues will occur.

**Comment by ajburls** [comment]
@iteles Have tested searching with upper and lower case and filtering by all sub-types and the error has not recurred.

**Comment by iteles** [comment]
@ajburls Excellent, can we go ahead and close this issue?

**Comment by ajburls** [comment]
yes
