### ISSUE TITLE
Email Encryption in Database

### ISSUE THREAD

**Issue by ghost** [dwyl/bestevidence#247]
As a project owner
I want the database of the application to have encrypted emails (in the same way that passwords are encrypted)
So that no one is able to see which email addresses link to which users

**Comment by iteles** [comment]
Removing this from sprint 5 milestone as it cannot be estimated until #248 is complete and could cause confusion if the feature is in the milestone.

**Comment by iteles** [comment]
4 hour estimate based on #248

**Comment by RobStallion** [comment]
Following the steps outlined [here](https://github.com/dwyl/bestevidence/issues/248#issuecomment-348208574) I was able to hash a users email address. 

However whilst working on this issue I realised that this step did not account for email addresses that were already in the database. To hash the emails in the database I need would need to create a migration file that looks at the current email addresses and hashed the ones that are not there already. 

Because of the knock on effects of this I have had to revise the time estimate of this issue.

**Comment by ajburls** [comment]
@RobStallion @iteles Ines, I presume you will follow this up with Yinka who did the purchase order for this addition? Also, it would be helpful for me to understand why the user numbers in the database have gaps (see attached spreadsheet of user IDs). Is this because Dwyl have put fake emails in and then deleted them during testing? 

I have put in a number of fake IDs for various purposes and it would be helpful if the following fake IDs can be removed from the database: 97, 80, 104, 791 (and any Dwyl test ids that are no longer in use), as part of the process of encrypting the emails.

[User IDs in database at 9 5 2018.xlsx](https://github.com/dwyl/bestevidence/files/1988179/User.IDs.in.database.at.9.5.2018.xlsx)

**Comment by ajburls** [comment]
@RobStallion  I have tested this today and the email addresses are now encrypted. The rest of the queries work as before so it would appear that this is all in order.
