### ISSUE TITLE
Email Encryption Solution Spike

### ISSUE THREAD

**Issue by ghost** [dwyl/bestevidence#248]
As a developer
I need a solution to solve the email encryption issue https://github.com/dwyl/bestevidence/issues/247
But it is not yet clear what the solution is
Therefore I need to spend some time carrying out a spike* to research and test various solutions for this

*A spike is a limited period of time (often between half a day and two days) during which a number of different methods are tried to solve a problem, in order to determine what the best solution is. The code that is written during this time is not used directly in the project, but the learnings are

**Comment by Danwhy** [comment]
After some research I've come up with the following solutions.

### Option 1
Hashing the emails in the database.

#### What this means
Using a one-way cryptographic function, we turn the email into a hexadecimal string that cannot be tied back to the email address it came from, without knowing the email in the first place.
A user will still be able to login to the site, as we will hash their email again when they login, and check if the database contains that hash.

#### Advantages
* These hashes will not be identifiable as their respective emails, so no one will know which emails are associated with which account, not even us.
* Each email address is uniquely hashed. An attacker managing to access one email address will have no advantage accessing the others.

#### Disadvantages
* Using a hash function still leaves the email open to a brute force attack, as emails cannot be made more secure like passwords can.
* We cannot use the email address in any way, unless again provided to us by the user (eg. if the user wanted to reset their password, we could do that as long as they give us their email address again).

#### Implementation
Using the [erlang `crypto.hash` function](http://erlang.org/doc/man/crypto.html) (available in Elixir), we hash the email address when the user is created. We don't want to salt the hashes, as that would make it too difficult to check the email address exists in the database when a user logs in, and as email addresses are unique anyway, no two of the hashes will be the same.
When a user logs in, we hash the email address they give us, and check the database for this hash. If it exists, we continue to log in as we normally would. This way, the plaintext of the email address is seen by nobody except the user who typed it in.
__Estimated time to implement:__ 4 hours.

### Option 2
Encrypting the emails with a secret key.

#### What this means
The email address is encrypted using a specific string known as a key. This key can also be used to decrypt the encrypted email address back to plaintext.

#### Advantages
* The email addresses cannot be brute forced. The only way to know for sure what the email address is, is to use the secret key.

#### Disadvantages
* Because we need to use people's email addresses to log them in, we need to store the secret key. We can store this as an environment variable, so it's not in the same place as the emails, but if our database is compromised by an attacker, it's a safe bet that our server would be too.
* The emails can still be seen by anyone with access to the secret key, such as the developers.
* Only one key can be used for every email address, meaning if one email is compromised, they all are.

#### Implementation
Using the Elixir module [cipher](https://github.com/rubencaro/cipher), we define a secret key (stored as an environment variable), then do much the same as above, encrypting the email on account creation and login, and comparing the two.
__Estimated time to implement:__ 4 hours.

In terms of security, __option 1__ provides us the most, and would be my recommended implementation. However, if the emails need to be used for anything (except password resets/other actions specifically requested by a user), we'd need to use __option 2__.
@ajburls Do you have any preference here?

**Comment by ajburls** [comment]
@Danwhy This is very timely information. Both would seem to do the job we want. However, I am meeting in an hour's time with the people who have responsibility for data protection issues at City, University of London, to discuss the app. I will show them the proposed solutions and check this end. I will comment here afterwards.

**Comment by ajburls** [comment]
@Danwhy I have now had a discussion with City's Information Compliance Officer and we would like to go for option 1 as the safer option. We do not anticipate needing to know individual's email addresses.

**Comment by ajburls** [comment]
@Danwhy When is this going to be implemented? (I just checked and email addresses are still visible and therefore potentially linkable to searches).

**Comment by iteles** [comment]
@ajburls I'm just going through here and making sure things are up to date. As we discussed via emails - as soon as you give the green light!

**Comment by ajburls** [comment]
@iteles Ines, I am meeting with Yinka and he says that he also gave the green light for this some time ago as did I for option 1. What is happening? I would like this to be the very next product delivered.

**Comment by iteles** [comment]
Closing in favour of #247, which we will now work on next week as agreed with @ajburls
