### ISSUE TITLE
In-app messaging and notifications

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#259]
As an health care organisation using this app with health care professionals,
I would like to be able to send messages to individuals (e.g. to someone who has made notes that could breach patient confidentiality to advise them how they could make notes more appropriately), to groups (e.g. everyone working in urology to advise them a new NICE guideline has just been published) or to everyone (e.g. to let them know that the hospital has been put on red alert following a major public health incident).
As email addresses are encrypted, this would need to be done via push notifications.
What time and resources are required to add push notifications or similar?

**Comment by Cleop** [comment]
I think that these different user groups that you are referring to would probably be best broken off into separate issues because the logic to implement the messages is likely to evolve differently. Although perhaps this issue could be an epic to link them all together.

Is it just your account @ajburls that you would like to have the permission to do this and therefore no one else would have access to this message writing page?

We would probably benefit from getting a rough idea of the designs for this before we estimate as well, so whether the notifications would just be under a messages icon like this:
<img src="https://user-images.githubusercontent.com/16775804/34310858-b5080958-e751-11e7-92fc-a240ffb10090.png" width=30px />
which could change colour or change to show a red dot when there is a notification that is unread. If this is the case, do we need to implement the logic for gauging whether a notification is read or not at this stage or would simply be getting the messages out be the first priority? Another way could be that a red dot would show when there are notifications that are new, new being dictated by a time frame ie. 1 day or 1 week old. Is there a possibility that some people may amass tonnes of notifications and therefore it would be easier for them to tell by timeframe when there are new ones rather than forcing them to open them all to remove the red icon.

Where would this message button sit in the app?

**Comment by ajburls** [comment]
@Cleop - it would be anyone with administrative rights. Currently me with access to entire user group, but we anticipate badging the app for different organizations, having a flag that identifies the content as coming from a particular badged app, and an administrator from each organisation will be given access to the backend data coming from that organisation.

"Is there a possibility that some people may amass tonnes of notifications and therefore it would be easier for them to tell by timeframe when there are new ones rather than forcing them to open them all to remove the red icon."

Unlikely to be many.
I don't know if there is a convention as to where message alert sits but very top right (currently end of the message about the app being in alpha) would seem to be prominent but not distracting.

I think people should be able to keep old messages, so some way of accessing them is required. (List of all messages in descending date order with flag to show if opened or not and on opening flag disappears and people get option to delete?)

**Comment by iteles** [comment]
Summary:
In-app messaging system that would allow each user to have an inbox to receive messages within the app and then both super admins (Amanda) and client admins (which, note, we have _not_ scoped into issue #260) would be able to send out messages to them.

This would include an unread message in-app notification for users, so read/unread functionality would need to be built in.

**Comment by RobStallion** [comment]
- Create room for each user (users would not be able to reply, similar to how an inbox works)
 - Add super admin to each room (meaning super admin can message each user)
 - Add client admin to rooms belonging to their users (e.g. barts admin is in all barts users rooms)
 - Create page where admins would be able to choose who to message. Super admin would have option to pick all, organisation or single, client admin would have organisation or single. (will need more discussion on what this would look like as it will effect implementation)
   - Create function that will allow admin to send message to multiple users in different rooms at once. (Will look into in more detail. Current solution would be to use a send single message function and iterate it over a list of users)
- Create page where user can read message. This will take them to their room and will update a variable in the database to say that they have read it.

**Comment by RobStallion** [comment]
Closing this issue now. No longer needed
