### ISSUE TITLE
Colours to be customisable for new clients

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#289]
Sub-task of #260 

As a super admin
I would like to be able to customise a number of colours for new clients
So that their UI can be more relevant to their users.

## Acceptance Criteria
+ [x] Super admin new client form includes input fields for hexes for Login page background, Button colour and Search bar on the search results pages
+ [x] Login page background, Button colours and Search bar on the search results pages for a given client matches the colours entered in the form
+ [x] Tested with 2 new clients to ensure the default, client 1 and client 2 all work correctly in parallel

**Comment by sophielevens** [comment]
Currently, if a user types an incorrect password then I am redirected to `/sessions` doesn't display the correct client colours

**Comment by iteles** [comment]
@sophielevens This is a great point, we hadn't thought of the forgotten password flow either! We'll need to open separate issues on this 😬

**Comment by sophielevens** [comment]
Hi @ajburls, we have come across some inconsistencies with the colours in the current design and we would just like to clarify which colours are correct. 

Please see the examples below. 


![image](https://user-images.githubusercontent.com/25961258/40302640-a520023c-5ce7-11e8-8a28-aa1b6685a4ff.png)

![image](https://user-images.githubusercontent.com/25961258/40303401-8a2af650-5cea-11e8-8665-eff03d09698d.png)


![image](https://user-images.githubusercontent.com/25961258/40302725-fb5e8614-5ce7-11e8-9154-4ba128e6f930.png)

In the first image the header section is a bright red but in the second it is maroon. 

Similarly, the button colours on the first and second images are the same but in the third image it is different. 

We just wanted to check if this is intentional, or if all headers are supposed to the same colour and all buttons are supposed to be the same colour?

**Comment by iteles** [comment]
I would suggest that for the purposes of the customisation, all headers should be the same colour and all buttons the same colour (but different to the headers).

**Comment by ajburls** [comment]
@sophielevens  - not deliberate!
I agree with @iteles: let's have headers in the darker red and buttons in lighter red. Then when i add new clients, I will add darker colour for their headers and lighter colour for buttons.

**Comment by RobStallion** [comment]
@ajburls Please test

**Comment by ajburls** [comment]
@RobStallion I have logged in a super admin and can now see a list of all the previously added clients and when I click on one I can edit it OK.

I do not know whether I am supposed to be able to see the end product yet to see whether edit has actually worked. If I am, I don't know how to do so. Also, the editing screen is just plain text input still.

If this issue is only about first sentence then it can be closed.

**Comment by ajburls** [comment]
@iteles @RobStallion Can't tell what has been done since last tested and found OK. I think that probably this issue just needs closing.
