### ISSUE TITLE
Add Client form error messages 

### ISSUE THREAD

**Issue by sophielevens** [dwyl/bestevidence#290]
As a super admin user, I want to see friendly error messages if I input any incorrect data 

relates #288

**Comment by ajburls** [comment]
@sophielevens Hi Sophie I tested this putting in wrong hex format and get message "has invalid format"

I am not sure this is particularly friendly. I think it would be better to put in something like "Please specify colour in a valid Hex format" so that another person who did not know what is required would get some guidance. I also think it would be good for error text to be in red as not very apparent at the moment unless you know you are looking for something.

**Comment by ajburls** [comment]
@sophielevens This is much better, thanks
