### ISSUE TITLE
Ability to edit colours for *existing* clients

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#296]
Sub-task of #260

As a super admin
I want to be able to edit colours for _existing_ clients once these have been set up in #289 
So that if I make a mistake or our clients change their minds, these can be fixed.

## Acceptance Criteria
+ [x] Super admin edit client form includes editable fields for hexes for
  + [x] Login page background
  + [x] Button colour
  + [x] Search bar on the search results pages
+ [x] Login page background, Button colours and Search bar on the search results pages for a given client matches the colours updated in the form

**Comment by sophielevens** [comment]
time estimate depending on completion of #297

**Comment by RobStallion** [comment]
@ajburls Please test

**Comment by ajburls** [comment]
@RobStallion Rob, I can now look at the the login/create and account page for a client and see the colour, but am unable to create an account as that link just leads me back to the generic staging page not a /barts page. This means I am unable to test some of the items in the check list above

e.g. Button colours and Search bar on the search results pages for a given client matches the colours updated in the form

**Comment by RobStallion** [comment]
@ajburls I cannot seem to replicate the issue you are having. These are the steps that I have taken...

I navigate to https://best-evidence-staging.herokuapp.com/barts and see
![image](https://user-images.githubusercontent.com/15571853/40538996-3e36aae0-600b-11e8-9c25-980497e3c936.png)

If I then click the `Create an Account` button I am taken to
![image](https://user-images.githubusercontent.com/15571853/40539064-7fd7c7a4-600b-11e8-8e37-23bd9324aaed.png)

Next, I click the `I agree` button and get
![image](https://user-images.githubusercontent.com/15571853/40539172-c017d7a0-600b-11e8-8c4b-b8f3b1c794eb.png)

If I fill in the form and click the `Start Searching` button I am taken to 
![image](https://user-images.githubusercontent.com/15571853/40539213-dcecdf4c-600b-11e8-876d-8164300ca55d.png)

Please let me know if anything is unclear or if I have misunderstood what you meant. Thanks

**Comment by ajburls** [comment]
@RobStallion No, you understood. The weird thing is that when I followed your link it worked (despite having reproduced the error several times before posting!). However the error happens now downstream so that when I then pressed "start searching" from the barts page, it takes me to the generic page. This
![image](https://user-images.githubusercontent.com/30235568/40540471-35a6692e-6010-11e8-9a5a-d4e2612821b0.png)


goes to 

![image](https://user-images.githubusercontent.com/30235568/40540551-7913ad84-6010-11e8-8307-724a31bd259c.png)

**Comment by RobStallion** [comment]
@ajburls Good spot. This was happening because your email address is already in use on the site so it was not letting you sign up again with that same email address. 

I have added a change now so that if a user goes to sign up route with an email that exists in the database already they will be directed back to the login page of the client they were on. e.g.

![image](https://user-images.githubusercontent.com/15571853/40543275-917fd57c-601b-11e8-810d-7d70babfaeb6.png)
as test@user.com is an existing user (in my local db), when I click the `Start Searching` button I am now taken to

![image](https://user-images.githubusercontent.com/15571853/40543336-cb752494-601b-11e8-8b30-3b1d99d8d628.png)

Where I will be able to log in, or request my password if I have forgotten it

**Comment by ajburls** [comment]
@RobStallion I find that I keep going out of the barts app to the base app i.e. clicking "start searching" on this page:

![image](https://user-images.githubusercontent.com/30235568/41201436-f6588b42-6caf-11e8-9b28-a9a0349986fa.png)


goes to 

![image](https://user-images.githubusercontent.com/30235568/41201427-baa8cb52-6caf-11e8-90aa-79a6493ca98c.png)
