### ISSUE TITLE
Stage 2 | Registering the uncertainty - PICO

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#373]
As a user critically appraising a topic
I would like to be able to define my PICOs
So that I can run a search for papers with more detail than the usual search.

![image](https://user-images.githubusercontent.com/25961258/43089010-82b212c2-8e9b-11e8-80cd-29f97e2975e1.png)

**Comment by RobStallion** [comment]
@nelsonic In the `picoSearchController` [here](https://github.com/dwyl/bestevidence/blob/bear-necessities/web/controllers/pico_search_controller.ex#L25-L66), we have a `Repo.insert` for a  `PicoSearch`. We are using the `case` statement to pattern match on the result of the `insert` function. The reason for my query is that the `changeset` for a `PicoSearch` does not need to do any validation (except to make sure inputs are the type they should be, e.g 'string', 'integer').

I am wondering if it would be okay to use the `Repo.insert!` function here instead? The downside to the `insert!` function is that it raises an error when the insert fails. The reason I am asking is because I cannot see how the insert will ever fail, unless there is an issue with the database itself. 

Please let me know if anything is unclear or if you would like to go over any of the code together. Thanks 👍

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
