### ISSUE TITLE
Implement Forgotten Password Functionality

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#76]
As a user
I need to be able to re-set my password if I have forgotten it
So I can get back into my account.

**Comment by markwilliamfirth** [comment]
@SimonLab please could you time estimate this?

**Comment by iteles** [comment]
Note: We will not be implementing the second to last checkbox as per the comment above.

The user will be taken only to an update password page (not logged in anywhere) and will be given the opportunity to update their password here. They will not be given immediate access to the account until their password has been changed, at which point they will be able to log in again.

**Comment by RobStallion** [comment]
Copied from [above](https://github.com/dwyl/bestevidence/issues/76#issuecomment-321629033) as I am unable to update the issue there.

- [ ] Forgotten password link on login page
- [ ] Clicking on link user taken to page where they enter the email address for which the password has been forgotten
- [ ]  User receives an email with a reset password link
- [ ] Write password twice so that no errors first time

**Comment by ajburls** [comment]
This is after entering email address and happens on various browsers

**Comment by parkhabit** [comment]
Environment variables were missing from Heroku. They have now been added so there shouldn't be an internal server error anymore.

**Comment by ajburls** [comment]
@iteles There is no internal server error, only the error that password re-set link times out. If that is covered elsewhere should this be closed?

**Comment by iteles** [comment]
Agreed @ajburls , that's covered in #275 so we can close this.

**Comment by ajburls** [comment]
Ok
